#!/usr/bin/env bash
hc() {
    herbstclient "$@"
}
ORANGE='#bd93f9'
xsetroot -solid '#5A8E3A'
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color $ORANGE
hc set frame_border_width 1
hc set always_show_frame 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.active.color $ORANGE
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color red
hc attr theme.inner_width 0
hc attr theme.inner_color white
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color white #'#141414'
hc attr theme.title_when 'multiple_tabs'
hc attr theme.title_height 21
hc attr theme.title_color '#ffffff'

hc set window_gap 10
hc set frame_padding 0

hc set tree_style '╾│ ├└╼─┐'

hc set frame_gap 10
hc attr theme.border_width 10
#herbstclient set window_gap 1

# monitor paddings set to 0 as i just set the monitor positions accordingly
hc pad 3 0 0 0 0
hc pad 2 0 0 0 0
hc pad 1 0 0 0 0
hc pad 0 0 0 0 0
